"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$time$hostname$memory_usage$all"

[character]
success_symbol = "[â¯](bright-blue bold)"
error_symbol = "[â¯](bright-blue bold)"

[package]
disabled = true

[time]
format = "[â¯$time](white dimmed) "
time_format = "%l:%M %p"
utc_time_offset = '-5'
disabled = true

[username]
format = "[â¯ $user]($style) "
style_user = "bright-green"
show_always = true

[hostname]
format = "[â¯ $ssh_symbol$hostname]($style) "
ssh_symbol = "ğŸŒ"
style = "bright-blue"
ssh_only = false

[directory]
format = "[â¯ $path]($style)[$read_only]($read_only_style) "
style = "bright-cyan"

[git_branch]
format = "[â¯ $symbol$branch(:$remote_branch)]($style) "
style = "bright-purple"

[git_status]
style = "bright-purple"

[rust]
format = "[â¯ $symbol($version )]($style)"
symbol = "rustc "
style = "bright-red"

[nodejs]
format = "[â¯ $symbol($version )]($style)"
symbol = "nodejs "
style = "bright-red"

[memory_usage]
format = "[â¯ mem ${ram} ${ram_pct}]($style) "
threshold = -1
style = "white"

[cmd_duration]
format = "[â¯ $duration]($style)"
style = "bright-yellow"